### ISSUE TITLE
We might want to replace map with city name entry

### ISSUE THREAD

**Issue by Gavin1937** [Gavin1937/Your-Moon-CSULA#56]
We can replace map with an input box asking user for city & country name of the image.
We can use [dataset in cityjs](https://github.com/MxAshUp/cityjs/blob/master/src/cities5000.csv)

**Comment by SebastianKane** [comment]
We should replace the map and coordinate fields with one autocomplete text field for cities. 

This autocomplete field should be automatically be populated with the nearest city if the coordinates are found in exif. Otherwise here should be some sort of autocomplete mechanism (dropdown or ghost text) that provides suggestions as the user starts typing.

Example of an autocomplete field:

https://www.w3schools.com/howto/howto_js_autocomplete.asp
